import Head from "next/head";
import Image from "next/image";
import { Result } from "postcss";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Our Gallery 1.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />
      <Results results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const request = await fetch(`https://beourgallery.herokuapp.com/api/users/`).then((res) =>
    res.json()
  );
  return {
    props: {
      results: request,
    },
  };
}
